const resObj = [
    {
      id: "1778546669",
      itemName: "Railway Cutlet New",
      description:
        "2 Pcs 120gm Serves With Tomato Ketchup. Crispy On The Outside, Packed With Zesty Veggie Goodness On The Inside!",
      basePrice: 47.62,
      sellingPrice: 50,
      taxRate: 2.38,
      taxPercentage: 0.05,
      rating:4.3,
      active: true,
      schedules: null,
      foodType: null,
      cuisine: "CHINESE,NORTH_INDIAN,SOUTH_INDIAN",
      quantity: 0,
      options: null,
      createdAt: null,
      createdBy: null,
      updatedAt: null,
      updatedBy: null,
      customisationDefaultBasePrice: null,
      customisations: null,
      bulkOnly: false,
      image:
        "https://hotplate-menu-images.s3.ap-south-1.amazonaws.com/ImageGryBG/Cutlet72827.png",
      count: null,
      tags: null,
      itemType: "VEG",
      suggestedItemIds: null,
      uniqueMenuItemId: null,
      foodTags: null,
      outletId: 95009459,
      orderByTime: null,
    },
    {
      id: "1780785334",
      itemName: "Railway Cutlet",
      description:
        "2 Pcs 120gm Serves With Tomato Ketchup. Crispy On The Outside, Packed With Zesty Veggie Goodness On The Inside!",
      basePrice: 47.62,
      sellingPrice: 50,
      taxRate: 2.38,
      taxPercentage: 0.05,
      active: true,
      schedules: null,
      foodType: null,
      cuisine: "CHINESE,MAHARASHTRIAN,NORTH_INDIAN,SOUTH_INDIAN",
      quantity: 0,
      options: null,
      createdAt: null,
      createdBy: null,
      updatedAt: null,
      updatedBy: null,
      customisationDefaultBasePrice: null,
      customisations: null,
      bulkOnly: false,
      rating:4.5,
      image:
        "https://hotplate-menu-images.s3.ap-south-1.amazonaws.com/ImageGryBG/Cutlet72827.png",
      count: null,
      tags: ["MUST_TRY"],
      itemType: "VEG",
      suggestedItemIds: null,
      uniqueMenuItemId: null,
      foodTags: null,
      outletId: 1592317196,
      orderByTime: null,
    },
    {
      id: "1792651418",
      itemName: "Mughlai Chicken Kofta Rice Bowl",
      description:
        "(500 gms)\nAn extraordinary twist youll fall in love with. Soft chicken meatballs dipped in pipping hot gravy served with rice & salad.",
      basePrice: 199,
      sellingPrice: 208.95,
      taxRate: 9.95,
      taxPercentage: 0.05,
      active: true,
      schedules: null,
      foodType: null,
      cuisine: "Beverages,Biryani Bowls,Desserts,Signature Bowls",
      quantity: 0,
      options: null,
      createdAt: null,
      createdBy: null,
      updatedAt: null,
      updatedBy: null,
      customisationDefaultBasePrice: null,
      customisations: null,
      bulkOnly: false,
      rating:3.5,
      image: "https://rp-media.faasos.io/catalog/images/VEKWVPDWMBVR.jpeg",
      count: null,
      tags: null,
      itemType: "NON_VEG",
      suggestedItemIds: null,
      uniqueMenuItemId: null,
      foodTags: null,
      outletId: 96025230,
      orderByTime: null,
    },
  ];

export default resObj;